apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: wf--6ce71a38-template
  generatename: ""
  namespace: ""
  selflink: ""
  uid: ""
  resourceversion: ""
  generation: 0
  creationtimestamp: "0001-01-01T00:00:00Z"
  deletiontimestamp: null
  deletiongraceperiodseconds: null
  labels: {}
  annotations: {}
  ownerreferences: []
  finalizers: []
  clustername: ""
  managedfields: []
objects:
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      creationTimestamp: null
      name: wf--6ce71a38-clone-push
    secrets:
      - name: wf--6ce71a38-image-registry
      - name: wf--6ce71a38-git-repo-github-com
  - apiVersion: triggers.tekton.dev/v1alpha1
    kind: EventListener
    metadata:
      creationTimestamp: null
      name: wf--6ce71a38-git-repo
    spec:
      namespaceSelector: {}
      resources: {}
      serviceAccountName: wf--6ce71a38-tekton-triggers-admin
      triggers:
        - bindings:
            - ref: wf--6ce71a38-git-event
          template:
            ref: wf--6ce71a38-run-clone-build-push
    status:
      configuration:
        generatedName: ""
  - apiVersion: v1
    data:
      known_hosts: Z2l0aHViLmNvbSBzc2gtcnNhIEFBQUFCM056YUMxeWMyRUFBQUFCSXdBQUFRRUFxMkE3aFJHbWRubTl0VURiTzlJRFN3Qks2VGJRYStQWFlQQ1B5NnJiVHJUdHc3UEhrY2NLcnBwMHlWaHA1SGRFSWNLcjZwTGxWREJmT0xYOVFVc3lDT1Ywd3pmaklKTmxHRVlzZGxMSml6SGhibjJtVWp2U0FIUXFaRVRZUDgxZUZ6TFFOblBIdDRFVlZVaDdWZkRFU1U4NEtlem1ENVFsV3BYTG12VTMxL3lNZitTZTh4aEhUdktTQ1pJRkltV3dvRzZtYlVvV2Y5bnpwSW9hU2pCK3dlcXFVVW1wYWFhc1hWYWw3MkorVVgyQisyUlBXM1JjVDBlT3pRZ3FsSkwzUktyVEp2ZHNqRTNKRUF2R3EzbEdIU1pYeTI4RzNza3VhMlNtVmkvdzR5Q0U2Z2JPRHFuVFdsZzcrd0M2MDR5ZEdYQThWSmlTNWFwNDNKWGlVRkZBYVE9PQ==
      ssh-privatekey: PFRPRE86IGluc2VydCB0aGUgcHJpdmF0ZSBzc2gga2V5IGZvciB5b3VyIGdpdCByZXBvPg==
    kind: Secret
    metadata:
      annotations:
        tekton.dev/git-0: github.com
      creationTimestamp: null
      name: wf--6ce71a38-git-repo-github-com
    type: kubernetes.io/ssh-auth
  - apiVersion: networking.k8s.io/v1
    kind: Ingress
    metadata:
      creationTimestamp: null
      labels:
        move2kube.konveyor.io/service: wf--6ce71a38
      name: wf--6ce71a38
    spec:
      rules:
        - host: localhost
          http:
            paths:
              - backend:
                  service:
                    name: el-wf--6ce71a38-git-repo
                    port:
                      name: port-8080
                path: /el-wf--6ce71a38-git-repo
                pathType: Prefix
    status:
      loadBalancer: {}
  - apiVersion: tekton.dev/v1beta1
    kind: Pipeline
    metadata:
      creationTimestamp: null
      name: wf--6ce71a38-clone-build-push
    spec:
      params:
        - description: registry-domain/namespace where the output image should be pushed.
          name: image-registry-url
          type: string
      tasks:
        - name: clone-1
          params:
            - name: url
              value: git@github.com:eloycoto/spring-helloworld.git
            - name: revision
              value: move2kubeUpdates
            - name: deleteExisting
              value: "true"
          taskRef:
            name: git-clone
          workspaces:
            - name: output
              workspace: wf--6ce71a38-shared-data
            - name: ssh-directory
              workspace: git-credentials
        - name: build-push-1
          params:
            - name: IMAGE
              value: $(params.image-registry-url)/demo
            - name: DOCKERFILE
              value: Dockerfile
            - name: CONTEXT
              value: .
          runAfter:
            - clone-1
          taskRef:
            name: kaniko
          workspaces:
            - name: source
              workspace: wf--6ce71a38-shared-data
            - name: dockerconfig
              workspace: docker-credentials
      workspaces:
        - description: This workspace will receive the cloned git repo and be passed to the kaniko task for building the image.
          name: wf--6ce71a38-shared-data
        - description: My ssh credentials
          name: git-credentials
        - description: My registry credentials (docker config.json)
          name: docker-credentials
  - apiVersion: triggers.tekton.dev/v1alpha1
    kind: TriggerBinding
    metadata:
      creationTimestamp: null
      name: wf--6ce71a38-git-event
    spec: {}
    status: {}
  - apiVersion: v1
    data:
      .dockerconfigjson: PFRPRE86IGluc2VydCB5b3VyIGRvY2tlciBjb25maWcganNvbj4=
    kind: Secret
    metadata:
      annotations:
        tekton.dev/docker-0: ""
      creationTimestamp: null
      name: wf--6ce71a38-image-registry
    type: kubernetes.io/dockerconfigjson
  - apiVersion: triggers.tekton.dev/v1alpha1
    kind: TriggerTemplate
    metadata:
      creationTimestamp: null
      name: wf--6ce71a38-run-clone-build-push
    spec:
      resourcetemplates:
        - apiVersion: tekton.dev/v1beta1
          kind: PipelineRun
          metadata:
            creationTimestamp: null
            name: wf--6ce71a38-clone-build-push-$(uid)
          spec:
            params:
              - name: image-registry-url
                value: quay.io/parodos
            pipelineRef:
              name: wf--6ce71a38-clone-build-push
            serviceAccountName: wf--6ce71a38-clone-push
            workspaces:
              - name: wf--6ce71a38-shared-data
                volumeClaimTemplate:
                  metadata:
                    creationTimestamp: null
                  spec:
                    accessModes:
                      - ReadWriteOnce
                    resources:
                      requests:
                        storage: 1Gi
                    storageClassName: default
                  status: {}
              - name: git-credentials
                secret:
                  secretName: git-credentials
              - name: docker-credentials
                secret:
                  secretName: docker-credentials
          status: {}
    status: {}
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: Role
    metadata:
      creationTimestamp: null
      name: wf--6ce71a38-tekton-triggers-admin
    rules:
      - apiGroups:
          - triggers.tekton.dev
        resources:
          - eventlisteners
          - triggerbindings
          - triggertemplates
        verbs:
          - get
      - apiGroups:
          - tekton.dev
        resources:
          - pipelineruns
        verbs:
          - create
      - apiGroups:
          - ""
        resources:
          - configmaps
        verbs:
          - get
          - list
          - watch
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: RoleBinding
    metadata:
      creationTimestamp: null
      name: wf--6ce71a38-tekton-triggers-admin
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: Role
      name: wf--6ce71a38-tekton-triggers-admin
    subjects:
      - kind: ServiceAccount
        name: wf--6ce71a38-tekton-triggers-admin
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      creationTimestamp: null
      name: wf--6ce71a38-tekton-triggers-admin
parameters: []
