
---
apiVersion: v1
kind: ServiceAccount
metadata:
    creationTimestamp: null
    name: wf--6ce71a38-clone-push
secrets:
    - name: wf--6ce71a38-image-registry
    - name: wf--6ce71a38-git-repo-github-com

...
